### ISSUE TITLE
KeyError caused by incorrect parameter name

### ISSUE THREAD

**Issue by ctodd** [aws-samples/langchain-agents#2]
The lambda function fails and returns a 502 error to the web client (see below).

The parameter name sent from the client is "messages" (plural), but the lambda function code in AIMessageProcessor.py references "message" (singular) on line 31:

`user_message_body = body['message']`

Error in Chrome console:

`Failed to load resource: the server responded with a status of 502 (Bad Gateway)`

Error from Cloudwatch log:

`[ERROR] KeyError: 'message'
Traceback (most recent call last):
  File "/var/task/AIMessageProcessor.py", line 17, in lambda_handler
    user_message = get_user_message(event)
  File "/var/task/AIMessageProcessor.py", line 31, in get_user_message
    user_message_body = body['message']`

**Comment by KBB99** [comment]
Thanks for catching this. Pushed an update to the front-end code to resolve the issue.
