### ISSUE TITLE
Missing sync trigger in Lambda

### ISSUE THREAD

**Issue by ctodd** [aws-samples/langchain-agents#3]
Not sure if this trigger is necessary, or just needs to be removed. Doesn't seem to impact function.

<img width="1241" alt="Screenshot 2024-01-28 at 11 13 56 AM" src="https://github.com/aws-samples/langchain-agents/assets/5911331/0e1ef357-f982-4286-9856-d84dc802680d">

**Comment by KBB99** [comment]
You're right saw that before and it looked unnecessary. I'll try removing it tomorrow and see if it breaks anything.

**Comment by KBB99** [comment]
After testing extensively it seems like the warning can be safely ignored. I've tried to remove it, but I do not see where it is defined in the CDK code and suspect it is being automatically defined and created somewhere along the way. From my research the sync trigger is designed to invoke a function when some user data is updated, for example name, email, or phone number. However in this case we don't want the Lambda to be invoked when changes are made to the user data as the Lambda is only designed to process messages aimed towards the LLM so the sync trigger can be safely deleted. If I find a way to remove it I will update the repo. Thanks for bringing this up and let me know if you run into any other issues.
